### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by FredrikL** [neo4j/neo4j-javascript-driver#304]
Using version 1.5.0
Node 8.1.4
Neo4j 3.1.1 (singel instance) & 3.2.3 (Casual cluster)
Linux / Debian

A couple of time per day we get this error, since it happens outside the normal process chain we're unable to catch it and the stack trace doesn't point to anything obvious.

```
TypeError: Cannot read property 'filter' of undefined
    at node_modules/neo4j-driver/lib/v1/internal/pool.js:115:44
    at Timeout._onTimeout (node_modules/neo4j-driver/lib/v1/internal/util.js:150:9)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
    at listOnTimeoutNT (timers.js:359:26)
    at _combinedTickCallback (internal/process/next_tick.js:99:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

**Comment by lutovich** [comment]
Hi @FredrikL,

Thanks for reporting this problem. We will investigate.

**Comment by Thiago-Caramelo** [comment]
We also get this error a few times per day.

At client side:

TypeError: Cannot read property 'filter' of undefined
    at /user_code/node_modules/neo4j-driver/lib/v1/internal/pool.js:115:44
    at Timeout._onTimeout (/user_code/node_modules/neo4j-driver/lib/v1/internal/util.js:150:9)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

At server side:

WARN  Illegal character 0x3 in state=START for buffer HeapByteBuffer@5707b2f0[p=1,l=1,c=8192,r=0]={\x03<<<>>>ET / HTTP/1.1\r\nHo...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}

WARN  badMessage: 400 Illegal character 0x3 for HttpChannelOverHttp@18fd5c5b{r=0,c=false,a=IDLE,uri=}

I'm not sure if they are related.

**Comment by lutovich** [comment]
@FredrikL, @Thiago-Caramelo this issue should be fixed by the mentioned PR. I think that error in the database logs in not related because it does not originate from Bolt server component.

**Comment by Guardiannw** [comment]
@lutovich What version of the driver should we expect this fix in?

**Comment by lutovich** [comment]
@Guardiannw in 1.5.2. We will try to release it this week.

**Comment by lutovich** [comment]
Version 1.5.2 with the mentioned fix is now released and available on NPM. Please report if it does not solve the problem. Thanks!

**Comment by FredrikL** [comment]
@lutovich  We're still seeing the same problem

```
TypeError: Cannot read property 'filter' of undefined
   at /node_modules/neo4j-driver/lib/v1/internal/pool.js:115:44
   at Timeout._onTimeout (/node_modules/neo4j-driver/lib/v1/internal/util.js:152:9)
   at ontimeout (timers.js:488:11)
   at tryOnTimeout (timers.js:323:5)
   at Timer.listOnTimeout (timers.js:283:5)
```

**Comment by Guardiannw** [comment]
We are also still seeing this problem, even after the new version.

**Comment by Guardiannw** [comment]
@lutovich Can you provide any details on the status?

**Comment by lutovich** [comment]
Sorry, I missed the message from @FredrikL. We will investigate

**Comment by lutovich** [comment]
This issue should be fixed in the newly released 1.6.0 version of the driver. I'll close this issue now. Please feel free to update it if the issue reoccurs.

**Comment by FredrikL** [comment]
Hi, sadly we still get this error even with the 1.6.0 driver

```
TypeError: Cannot read property 'filter' of undefined at Timeout._onTimeout (node_modules/neo4j-driver/lib/v1/internal/pool.js:113:47)
 at ontimeout (timers.js:475:11)
 at tryOnTimeout (timers.js:310:5)
 at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by lutovich** [comment]
Hi @FredrikL, I'm really sorry 😢
We will investigate.

**Comment by lutovich** [comment]
Hi @FredrikL,

Driver 1.6.1 with the mentioned fix is now available on NPM. Could you please try it out?

**Comment by FredrikL** [comment]
Hi @lutovich 

Upgraded yesterday and we haven't seen any errors since so it seems to have fixed our problem 👍

**Comment by hadirsa** [comment]
I have this issue with V4.0.1
